services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra_dev
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
    networks:
      - dev-network
    volumes:
      - ./cassandra-seed.dev.sql:/scripts/seed.sql
    

  redis:
    image: redis:latest
    container_name: redis_dev
    ports:
      - "6379:6379"
    networks:
      - dev-network

  spark-master:
    image: apache/spark:latest
    container_name: spark_master
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - dev-network

  spark-worker:
    image: apache/spark:latest
    container_name: spark_worker
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - dev-network

  app:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: fast_api_app
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true
    command: tail -f /dev/null
    volumes:
      - ../../:/app
    environment:
      - PYTHONPATH=/app
      - CASSANDRA_HOST=cassandra_dev
      - REDIS_HOST=redis_dev  # ДОДАНО: щоб API бачило Redis
    depends_on:
      - cassandra
      - redis
      - spark-master
    networks:
      - dev-network

# ДОДАНО: Спільна мережа для всіх сервісів розробки
networks:
  dev-network:
    driver: bridge