version: '3.8'

services:
  # Cassandra Database Service for development
  cassandra_db:
    image: cassandra:latest
    container_name: cassandra_dev
    ports:
      - "9042:9042" # Port for Cassandra connection
    environment:
      - CASSANDRA_CLUSTER_NAME=DevCluster
    volumes:
      - cassandra_dev_data:/var/lib/cassandra

  # Redis Service for caching (TTL 5 mins requirement)
  redis_cache:
    image: redis:latest
    container_name: redis_dev
    ports:
      - "6379:6379" # Port for Redis connection
    volumes:
      - redis_dev_data:/data

volumes:
  cassandra_dev_data:
  redis_dev_data: